apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloud-config-operator
  template:
    metadata:
      labels:
        name: cloud-config-operator
    spec:
      serviceAccountName: cloud-config-operator
      containers:
        - name: cloud-config-operator
          # Replace this with the built image name
          image: cloud-config-operator:0.2.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cloud-config-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cloud-config-operator"
